### ISSUE TITLE
oCore.mElements no longer available

### ISSUE THREAD

**Issue by Lonwyr** [msg-systems/ui5-testrecorder#14]
Hello,

I tested your test recorder with the version 1.67 and it seems the private map used oCore.mElements is no longer available. Thus, the replay is no longer working.

Best regards,
Christian

error Code: oCore.mElements was a private member and has been removed. Use one of the methods in sap.ui.core.Element.registry instead

**Comment by martenAdrian** [comment]
Hello Lonwyr,

does the error occur on the application or UI5 Testrecorder. 

The information is important to determine the location for the root of the issue.
