### ISSUE TITLE
sap.m.Dialog interaction not recognized

### ISSUE THREAD

**Issue by BenHarten** [msg-systems/ui5-testrecorder#18]
Hi,

on the app I'm trying to test, I have a sap.m.Dialog. Trying to interact with it does however not work. Anywhere i click on the Dialog I always just get the message "please finalize the step in the popup before proceeding..." and nothing comes up in the chrome extension, it simply stays on "recording information".

Best regards,
Uli

**Comment by martenAdrian** [comment]
Hello Uli, 

can you add a little more information to the issue? 
Possible Error messages (TestrecorderSide and ApplicationSide), UI5 version, etc.
Maybe the issue is replayable at the sample apps of the UI5-docu side. 

This error can happen throughout the whole application process, by a lot of different circumstances. 

Thanks a lot. 
Adrian

**Comment by BenHarten** [comment]
Hi Adrian,
thanks for the quick response. I was wondering if you are still actively working on this project - now I have my answer. :) 
Actually, when I try to perform any test recording on the UI5 sdk, I get the same message.
E.g.: https://openui5.hana.ondemand.com/#/entity/sap.m.Dialog/sample/sap.m.sample.DialogMessage
Clicking on the first button "Message Dialog" leads to the same message an no response from the test recorder. I'm working with Chrome on a Mac, the UI5 version on the sdk site is 1.69.1.

Best,
Uli

**Comment by martenAdrian** [comment]
Hi Uli,

we uploaded a fixed version of the UI5-Testrecorder to the WebStore.
Version 0.4.5 fixes your issue.

Mit freundlichen Grüßen
Adrian Marten

Von: BenHarten <notifications@github.com>
Gesendet: Freitag, 30. August 2019 15:15
An: msg-systems/ui5-testrecorder <ui5-testrecorder@noreply.github.com>
Cc: Adrian Marten <Adrian.Marten@msg.group>; Comment <comment@noreply.github.com>
Betreff: Re: [msg-systems/ui5-testrecorder] sap.m.Dialog interaction not recognized (#18)


Hi Adrian,
thanks for the quick response. I was wondering if you are still actively working on this project - now I have my answer. :)
Actually, when I try to perform any test recording on the UI5 sdk, I get the same message.
E.g.: https://openui5.hana.ondemand.com/#/entity/sap.m.Dialog/sample/sap.m.sample.DialogMessage
Clicking on the first button "Message Dialog" leads to the same message an no response from the test recorder. I'm working with Chrome on a Mac, the UI5 version on the sdk site is 1.69.1.

Best,
Uli

**Comment by BenHarten** [comment]
That was quick. Thank you! I will check it out.
However, on the web store, it seems to be still on version 0.4.2. Maybe it just takes a while to be updated there. But I can see your fix already on github.
Keep up the good work!

Uli
