### ISSUE TITLE
Correct catching of <a>-clicks

### ISSUE THREAD

**Issue by martenAdrian** [msg-systems/ui5-testrecorder#44]
While normal control on-click events are catched correctly, direct link clicks are performed before the UI5-Testrecorder is able to handle it by himself.

**Comment by martenAdrian** [comment]
Correct catching includes to use "oEvent.preventDefault" which removes the default browser behaviour for links (should be working for Firefox, Chorme, Safari). 
Problem is the handling of the click event by the sap.m.Link itself, which happens before and fires an additional event, which can currently not catched by us.

**Comment by martenAdrian** [comment]
Problem arrises, because we used to capture the events during the bubbling phase. 
If we catch it during the capture phase and prevent further processing it should work.

**Comment by claushunsen** [comment]
After merging PR #52, this issue can be closed.
