### ISSUE TITLE
UI of UI5-Testrecorder becomes lazy, if lot of items have to be shown

### ISSUE THREAD

**Issue by martenAdrian** [msg-systems/ui5-testrecorder#45]
Within the test case we had 384, found items and the selection of attributes and other control properties becomes lazy and partially unusable.

**Comment by martenAdrian** [comment]
Added some code improvements with #50, but not to much. Still the screen becomes laggy if we have to much items to select. 

A lot of this behaviour is comming up by all the automation to setup a "nearly" complete action screen. Maybe we can fix this, by reworking the workflow itself.

**Comment by claushunsen** [comment]
This is basically fixed, apart from some small changes coming with PR #53.
