### ISSUE TITLE
Save Button remains "busy"

### ISSUE THREAD

**Issue by martenAdrian** [msg-systems/ui5-testrecorder#55]
After Canceling the "Rating dialog" the Save Button of the TestStep remains busy.

![image](https://user-images.githubusercontent.com/48311788/80476265-6f882500-894a-11ea-827f-3bf0c5873779.png)

**Comment by martenAdrian** [comment]
Additionally this also comes up if you restart the already recorded test, because it never becomes unlocked.

**Comment by claushunsen** [comment]
This is fixed in commit aff905ce459b83d80f5beb3328c0f3846dca72ad of PR #53.
