### ISSUE TITLE
Difference Binding Context/Path at Popup and TestStep Screen

### ISSUE THREAD

**Issue by martenAdrian** [msg-systems/ui5-testrecorder#61]
There is a different meaning within the popup after selecting an item and the setting for the teststep attributes table.

Maybe the Binding stuff has to be refactored altogether.

**Comment by claushunsen** [comment]
> * Combine any binding-related criteria into a single one that only checks for binding paths (e.g., `default>/todos/1/title`). The user should be able to see the resulting value, for instance, via a corresponding label.

I have pushed a [commit ](https://github.com/msg-systems/ui5-testrecorder/commit/d386c0cebe90594795e41177c22929a125c7e372)to the branch `binding-refactorings` that is a further step towards the implementation of the idea sketched above. The binding is now checked against the fully-qualified binding path, including a prefix with the model name and the
binding context (e.g., `"defaultModel>/todos/1/title"`).

There are still some issues open for this:
- Code generation is not adapted yet. Maybe, we defer this until we have more work on Issue #38. 
- [Composite bindings](https://ui5.sap.com/#/api/sap.ui.model.CompositeBinding) are not working properly yet as they do not have a reliable path -- which is currently needed in the code though. We need to discuss whether and how to support this.
   https://github.com/msg-systems/ui5-testrecorder/blob/d386c0cebe90594795e41177c22929a125c7e372/scripts/injected/pageInject.js#L2191-L2199

**Comment by claushunsen** [comment]
With the changes in 44fb194e8b8498712052e7ff3173e2032d6d5db6, this is likely fixed. I will put this issue into the review state.
