### ISSUE TITLE
Do not display unavailable criteria in the test-step attributes

### ISSUE THREAD

**Issue by claushunsen** [msg-systems/ui5-testrecorder#64]
In the test-step view, there are several criteria shown, which can be used for selecting the correct control from the page or which are used for assertions. Under some circumstances, it is possible that there are no valid selections available for a criterion. Nevertheless, the criterion is shown while the subcriterion and its value is left empty. 

For better user experience, unavailable criteria should not be presented to the user. For example, if there is no binding in a selected control, the criterion `Binding` should not be shown.

**Comment by martenAdrian** [comment]
The problem is only resolvable by disabling the items which can not be selected. 
As shown at the picture.
![Issue_64](https://user-images.githubusercontent.com/48311788/81385897-6d755180-9114-11ea-8c52-450c4bc39300.png)

**Comment by claushunsen** [comment]
For me, this is fixed by commit 1c45d58204d7fa07254f5730e04d51afac70f0a1. I will close here.
