### ISSUE TITLE
Make all available criteria available in the find dialog

### ISSUE THREAD

**Issue by claushunsen** [msg-systems/ui5-testrecorder#69]
When adding attributes for filtering controls, the find dialog is shown (see picture below). After commit ebf271ec060e7252c92544276fd8963e55a53cd9, this the only way to add attributes to the list. Unfortunately, the dialog does not show all available criteria but only `Binding path` and `Property` – such that `Aggregation`, `Identifier`, `Metadata`, and `View data` are missing. For me, this is a bug right now.

The missing criteria need to be added to make the dialog fully functional. Alternatively, the old behavior before commit ebf271ec060e7252c92544276fd8963e55a53cd9 could be re-instantiated by reverting the commit.

What is your opinion on how to resolve this, @martenAdrian?

----------------

![Annotation 2020-05-13 131616](https://user-images.githubusercontent.com/58171110/81805882-f4af3480-951b-11ea-98e4-5d2739b21bd7.jpg)

----------------

This is kinda related to issue #65, but deals with already available data, while issue #65 demands additional information to be retrieved.

**Comment by claushunsen** [comment]
I gave this another thought: We also have the different targets available (i.e., own element and the four next parents), so we would need to integrate this information into the find dialog, too. 

The refactoring that is needed to incorporate also the target information into the find dialog is rather extensive. Hence, I suggest reverting commit ebf271ec060e7252c92544276fd8963e55a53cd9 for now. This issue could be revisited then after the next release.

What are your thoughts?

**Comment by martenAdrian** [comment]
In respect to commit 9445a07, we don't have aggregations or associations within the dialog. 

Association can not be checked, and aggregations are currently only part of the commit. Should follow afterwards.
